[package]
name = "minesweepe-rs"
version = "0.4.1"
edition = "2021"
description = "rust minesweeper. minesweeper in rust."
license = "MIT"
repository = "https://github.com/meihapps/minesweepe-rs"
readme = "README.md"
keywords = ["minesweeper", "tui", "game", "terminal"]
categories = ["games", "command-line-utilities"]

[dependencies]
ratatui = { version = "0.30", features = ["crossterm"] }
crossterm = "0.28"
ratatui-macros = "0.6"
color-to-tui = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5"
anyhow = "1"
rand = "0.8"
rayon = "1"
tachyonfx = { version = "0.25", features = ["std-duration"] }

[profile.release]
debug = true
